// Generated by CoffeeScript 1.4.0
var hound;

hound = require('hound');

module.exports = {
  watch: function(path, callback) {
    try {
      return hound.watch(path);
    } catch (error) {
      return callback(error);
    }
  }
};
