// Generated by CoffeeScript 1.4.0
var hound;

hound = require('hound');

module.exports = function(notice, path, callback) {
  try {
    return hound.watch(path).on('change', function(file, stats) {
      return callback('change', file, stats);
    });
  } catch (error) {
    return callback(error);
  }
};
