// Generated by CoffeeScript 1.6.3
var hound;

hound = require('hound');

module.exports = function(notice, path, callback) {
  var error;
  try {
    return hound.watch(path).on('change', function(file, stats) {
      return callback('change', file, stats);
    });
  } catch (_error) {
    error = _error;
    return callback(error);
  }
};
