// Generated by CoffeeScript 1.6.3
var path, spawn;

spawn = require('child_process').spawn;

path = require('path');

module.exports = function(notice, opts, callback) {
  var child, command;
  command = path.normalize(__dirname + '/../../node_modules/.bin/coffee');
  child = spawn(command, opts["arguments"]);
  child.on('exit', function(code, signal) {
    if (typeof opts.exit === 'function') {
      opts.exit(child.pid, code, signal);
    }
    if (code !== 0) {
      return notice.event.bad('child exited', {
        opts: opts,
        pid: child.pid,
        code: code,
        signal: signal || ''
      });
    }
    return notice.event('child exited', {
      opts: opts,
      pid: child.pid,
      code: code,
      signal: signal || ''
    });
  });
  child.stderr.on('data', function(data) {});
  child.stdout.on('data', function(data) {});
  return callback(null, child);
};
