// Generated by CoffeeScript 1.4.0
var path, spawn;

spawn = require('child_process').spawn;

path = require('path');

module.exports = function(opts, callback) {
  var command;
  command = path.normalize(__dirname + '/../../node_modules/.bin/coffee');
  return callback(null, spawn(command, opts["arguments"]));
};
