// Generated by CoffeeScript 1.4.0
var Logger, winston;

winston = require('winston');

module.exports = Logger = (function() {

  function Logger(opts) {
    var transports;
    if (opts == null) {
      opts = {};
    }
    transports = [];
    if (typeof opts.console !== 'undefined') {
      transports.push(new winston.transports.Console({
        level: opts.console.level,
        colorize: opts.console.colorize
      }));
    }
    if (typeof opts.file !== 'undefined') {
      transports.push(new winston.transports.File({
        filename: opts.file.filename,
        level: opts.file.level
      }));
    }
    this.logger = new winston.Logger({
      transports: transports
    });
    return this.logger;
  }

  return Logger;

})();
