require('nez').realize 'Coffee', (Coffee, test, it, should) -> 

    it 'displays coffee-script coffee script compile error', (done, fs) ->

        fs.readFileSync = -> 

            return """ 

                require 'milk'
                require 'sugar'
                require mug'
                require 'teaspoon'
                require 'kettle'

            """

        Coffee.compile {}, 

            src: '/path/to/repo/src'
            dst: '/path/to/repo/lib'
            file: '/path/to/repo/src/dir/file.coffee', (error) -> 

                should.exist error
                test done

    it 'compiles coffee-script', (done, fs) -> 

        fs.readFileSync = -> 

            return """ 

                => 

            """

        fs.writeFileSync = (file, content) ->

            file.should.equal '/path/to/repo/lib/dir/file.js'
            content.should.equal '// Generated by CoffeeScript 1.6.2\nvar _this = this;\n\n(function() {});\n'
            test done

        Coffee.compile {}, 

            src: '/path/to/repo/src'
            dst: '/path/to/repo/lib'
            file: '/path/to/repo/src/dir/file.coffee', (error) -> 

