// Generated by CoffeeScript 1.6.3
var EOL;

EOL = require('os').EOL;

exports.filename = function() {
  var call, filename, line, match, next, _i, _len, _ref;
  _ref = Error.apply(this).stack.split(EOL);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    line = _ref[_i];
    if (!(match = line.match(/at\s(.*)\s\((.*?):/))) {
      continue;
    }
    call = match[1];
    filename = match[2];
    if (next++ === 2) {
      return filename;
    }
    if (call === 'Object.exports.filename' && filename.match(/nezcore.*caller.js$/)) {
      next = 0;
    }
  }
};
