// Generated by CoffeeScript 1.4.0
var core;

module.exports = core = {
  logger: require('./logger/logger'),
  runtime: require('./runtime/runtime'),
  injector: require('./injector/injector'),
  config: require('./config/config')
};
