// Generated by CoffeeScript 1.4.0
var core;

module.exports = core = {
  stacker: require('./stacker/stacker'),
  monitor: require('./monitor/monitor'),
  compiler: require('./compiler/compiler'),
  parser: require('./parser/parser'),
  spawn: require('./spawn/spawn'),
  checksum: require('./checksum/checksum')
};
