// Generated by CoffeeScript 1.6.3
var Config, fs, runningConfig;

fs = require('fs');

Config = (function() {
  function Config(opts) {
    var key;
    for (key in opts) {
      this[key] = opts[key];
    }
  }

  Config.prototype.fromFile = function(fileName) {
    var content, error;
    try {
      return content = fs.readFileSync(fileName);
    } catch (_error) {
      error = _error;
      console.log('error loading config from file:', fileName);
      return process.exit(100);
    }
  };

  return Config;

})();

if (typeof runningConfig === 'undefined') {
  runningConfig = new Config({
    secret: 'SEEKRIT',
    adaptor: 'socket.io',
    home: 'http://localhost:10101'
  });
}

module.exports = {
  load: function(opts) {
    if (opts.file) {
      runningConfig.fromFile(opts.file);
    }
  },
  get: function(key) {
    return runningConfig[key];
  },
  hup: function() {}
};
