// Generated by CoffeeScript 1.4.0
var Config, config, fs;

fs = require('fs');

config = null;

Config = (function() {

  function Config() {}

  Config.fromFile = function(opts) {
    var content;
    try {
      return content = fs.readFileSync(opts.file);
    } catch (error) {
      console.log('error loading config from file:', opts.file);
      return process.exit(100);
    }
  };

  return Config;

})();

module.exports = {
  load: function(opts) {
    if (opts.file) {
      config = Config.fromFile(opts);
    }
  }
};
