// Generated by CoffeeScript 1.4.0
var Config, fs, runningConfig;

fs = require('fs');

Config = (function() {

  function Config(opts) {
    var key;
    this.objective = {
      module: process.env.NEZ_OBJECTIVE_MODULE || 'eo',
      "class": process.env.NEZ_OBJECTIVE_CLASS || 'dev'
    };
    for (key in opts) {
      this[key] = opts[key];
    }
  }

  Config.prototype.fromFile = function(fileName) {
    var content;
    try {
      return content = fs.readFileSync(fileName);
    } catch (error) {
      console.log('error loading config from file:', fileName);
      return process.exit(100);
    }
  };

  return Config;

})();

if (typeof runningConfig === 'undefined') {
  runningConfig = new Config;
}

module.exports = {
  load: function(opts) {
    if (opts.file) {
      runningConfig.fromFile(opts.file);
    }
  },
  get: function(key) {
    return runningConfig[key];
  },
  hup: function() {
    return runningConfig = new Config;
  }
};
