// Generated by CoffeeScript 1.6.3
var LeafDetect, argsOf, async, defer, sequence;

argsOf = require('also').util.argsOf;

async = require('also').inject.async;

defer = require('when').defer;

sequence = require('when/sequence');

LeafDetect = require('./phrase_leaf_detect');

module.exports = {
  create: function(context, notice, realizerFn, tester) {
    var runHooks, stack, stacker;
    stack = [];
    context.isLeaf || (context.isLeaf = LeafDetect["default"]);
    runHooks = function(hookType, stack, done) {
      var phrase;
      return sequence((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = stack.length; _i < _len; _i++) {
          phrase = stack[_i];
          _results.push((function(phrase) {
            return function() {
              var deferral;
              deferral = defer();
              phrase[hookType](deferral.resolve);
              return deferral.promise;
            };
          })(phrase));
        }
        return _results;
      })()).then(done, done);
    };
    stacker = function(elementName, control) {
      var pushFn;
      pushFn = async({
        parallel: false,
        timeout: control.timeout || 0,
        error: function(error) {
          return console.log(error.stack);
        },
        beforeAll: function(done) {
          if (typeof control.beforeAll === 'function') {
            if (!control.global) {
              return control.beforeAll(done);
            }
            return control.beforeAll.call(null, done);
          }
          return done();
        },
        beforeEach: function(done, inject) {
          if (typeof inject.args[2] !== 'function') {
            inject.args[2] = inject.args[1] || function() {
              control.defer.resolve();
              return stack.pop();
            };
            inject.args[1] = {};
          }
          inject.args[1].defer = inject.defer;
          stack.push({
            element: elementName,
            phrase: inject.args[0],
            defer: inject.defer,
            queue: inject.queue,
            current: inject.current,
            beforeEach: control.beforeEach || function(done) {
              return done();
            },
            afterEach: control.afterEach || function(done) {
              return done();
            }
          });
          if (control.leafOnly) {
            return context.isLeaf({
              element: elementName,
              phrase: inject.args[0],
              fn: inject.args[2]
            }, function(leaf) {
              if (leaf) {
                control.leaf = true;
                return runHooks('beforeEach', stack, done);
              }
              return done();
            });
          } else if (typeof control.beforeEach === 'function') {
            if (!control.global) {
              return control.beforeEach(done);
            }
            return control.beforeEach.call(null, done);
          } else {
            return done();
          }
        },
        afterEach: function(done, inject) {
          var element, parent;
          if (inject.current.timeout) {
            pushFn.timeout = true;
            if (typeof tester === 'function') {
              tester(pushFn);
            }
          }
          element = stack.pop();
          if (element.queue.remaining === 0) {
            console.log('TODO: fix parent resolve before child');
            parent = stack[stack.length - 1];
            if (parent != null) {
              parent.defer.resolve();
            }
          }
          if (control.leaf) {
            return runHooks('afterEach', stack.concat([element]), done);
          }
          if (typeof control.afterEach === 'function') {
            if (!control.global) {
              return control.afterEach(done);
            }
            return control.afterEach.call(null, done);
          }
          return done();
        },
        afterAll: function(done, inject) {
          if (typeof control.afterAll === 'function') {
            if (!control.global) {
              return control.afterAll(done);
            }
            return control.afterAll.call(null, done);
          }
          return done();
        }
      }, function(phrase, nestedControl, fn) {
        var childElementName;
        childElementName = argsOf(fn)[0];
        nestedControl.global = control.global;
        nestedControl.leafOnly = control.leafOnly;
        return fn(stacker(childElementName, nestedControl));
      });
      Object.defineProperty(pushFn, 'stack', {
        get: function() {
          return stack;
        },
        enumerable: false
      });
      Object.defineProperty(pushFn, 'top', {
        get: function() {
          return stack[stack.length - 1];
        },
        enumerable: false
      });
      return pushFn;
    };
    return stacker(argsOf(realizerFn)[0], context);
  }
};
