// Generated by CoffeeScript 1.6.3
var fn;

fn = require('../parser/js').fn;

module.exports = {
  "default": function(params, isLeaf) {
    var parser;
    if (params.phrase == null) {
      return isLeaf(false);
    }
    parser = fn.parser();
    parser.on('closure', function(heap) {
      return console.log(heap);
    });
    parser.on('end', function() {
      return isLeaf(true);
    });
    return parser.parse(params.fn.toString());
  }
};
