// Generated by CoffeeScript 1.4.0
var crypto, fs;

fs = require('fs');

crypto = require('crypto');

module.exports = {
  file: function(filename) {
    var md5sum;
    md5sum = crypto.createHash('md5');
    md5sum.update(fs.readFileSync(filename).toString());
    return md5sum.digest('hex');
  }
};
